[about]
name = "wzq152"
avatar = "wzq152.jpeg"
hobbies = ["🎨 Desgin", "💻 Programming", "🏸 Badminton"]
skills = ["C#", "Rust", "TypeScript", "Vue"]

[social]
github = "djdjz7"
website = "https://djdjz7.top"
